namespace WHAL_Int.Maj;

public class srucTable
{
    private List<Coop> trackedCoops = new();

    private const string the_table =
@"Last updated: <t:{0}:R>

`  Coop   | Boosted | Tokens | Duration  | Finish`{1}
`Primary order based off of duration`
*`!!sruc` to summon an update!*
*Note that this is NOT a Wonky command, and was generated by WHAL-Int*";
    private const string bottom_half_of_table = "";

    public srucTable(string contractId, params string[] coopIds)
    {
        foreach (string coopId in coopIds)
        {
            trackedCoops.Add(new Coop(contractId, coopId));
        }
    }

    private string getRows()
    {
        string rows = "";

        foreach (Coop coop in trackedCoops)
        {
            rows += ("\n" + (
                $"[⧉](<https://eicoop-carpet.netlify.app/{coop.ContractId()}/{coop.CoopId()}>)`{coop.StrippedCoopId()} |" +
                $"{utils.CenteredString(coop.BoostedCount().ToString(), 9)}|" +
                $"{utils.CenteredString(coop.TotalTokens().ToString(), 8)}|" +
                $"{utils.CenteredString(coop.Duration(), 11)}|`" +
                $"<t:{coop.UnixCompletionTime()}:f>"
            ));
        }

        return rows;
    }

    public string GetSrucTable()
    {
        return string.Format(the_table, utils.ConvertToUnixTimestamp(DateTime.UtcNow),getRows());
    }
}
